[package]
name = "snarkvm-circuit-account"
version = "0.9.0"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Account circuit library for a decentralized virtual machine"
license = "GPL-3.0"
edition = "2021"

[dependencies.console]
package = "snarkvm-console-account"
path = "../../console/account"
version = "0.9.0"
optional = true

[dependencies.snarkvm-circuit-algorithms]
path = "../algorithms"
version = "0.9.0"
default-features = false

[dependencies.snarkvm-circuit-network]
path = "../network"
version = "0.9.0"
default-features = false

[dependencies.snarkvm-circuit-types]
path = "../types"
version = "0.9.0"
default-features = false

[dev-dependencies.snarkvm-utilities]
path = "../../utilities"

[dev-dependencies.anyhow]
version = "1.0.64"

[features]
default = [
    "enable_console",
    "snarkvm-circuit-algorithms/default",
    "snarkvm-circuit-network/default",
    "snarkvm-circuit-types/default"
]
enable_console = [ "console" ]
enclave = [
    "snarkvm-circuit-algorithms/enclave",
    "snarkvm-circuit-network/enclave",
    "snarkvm-circuit-types/enclave"
]
