[package]
name = "snarkvm-circuits-address"
version = "0.7.5"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Address circuit for a decentralized virtual machine"
license = "GPL-3.0"
edition = "2021"

[dependencies.snarkvm-circuits-environment]
path = "../environment"
version = "0.7.5"

[dependencies.snarkvm-circuits-group]
path = "../group"
version = "0.7.5"

[dependencies.nom]
version = "7.1"

[dev-dependencies.snarkvm-utilities]
path = "../../utilities"
version = "0.7.5"
