[package]
name = "snarkvm-utilities"
version = "0.2.1"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Utilities for a decentralized virtual machine"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkVM"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [ "cryptography::cryptocurrencies", "operating-systems" ]
include = [ "Cargo.toml", "src", "README.md", "LICENSE.md" ]
license = "GPL-3.0"
edition = "2018"

[dependencies.snarkvm-derives]
path = "../derives"
version = "0.2.1"
optional = true

[dependencies.bincode]
version = "1.3.2"

[dependencies.rand]
version = "0.8"
default-features = false
features = [ "std_rng" ]

[dependencies.thiserror]
version = "1.0"

[dev-dependencies.rand_xorshift]
version = "0.3"
default-features = false

[features]
default = [ "std", "derive" ]
std = [ ]
derive = [ "snarkvm-derives" ]
