[package]
name = "snarkvm-circuits-integers"
version = "0.7.5"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Integer circuits for a decentralized virtual machine"
license = "GPL-3.0"
edition = "2021"

[dependencies.snarkvm-circuits-boolean]
path = "../boolean"
version = "0.7.5"

[dependencies.snarkvm-circuits-environment]
path = "../environment"
version = "0.7.5"

[dependencies.snarkvm-circuits-field]
path = "../field"
version = "0.7.5"

[dependencies.nom]
version = "7.1"

[dependencies.num-traits]
version = "0.2"

[dev-dependencies.snarkvm-utilities]
path = "../../utilities"
version = "0.7.5"
