version: 2.1
commands:
  setup_environment:
    description: "Setup testing environment"
    parameters:
      cache_key:
        type: string
        default: snarkvm-stable-cache
    steps:
      - run: set -e
      - setup_remote_docker
      - run:
          name: Prepare environment and install dependencies
          command: |
            export SCCACHE_CACHE_SIZE=200M
            export WORK_DIR="$CIRCLE_WORKING_DIRECTORY/.cache/sccache"
            export SCCACHE_DIR="$CIRCLE_WORKING_DIRECTORY/.cache/sccache"
            mkdir -p "$CIRCLE_WORKING_DIRECTORY/.bin"
            wget https://github.com/mozilla/sccache/releases/download/0.2.13/sccache-0.2.13-x86_64-unknown-linux-musl.tar.gz
            tar -C "$CIRCLE_WORKING_DIRECTORY/.bin" -xvf sccache-0.2.13-x86_64-unknown-linux-musl.tar.gz
            mv $CIRCLE_WORKING_DIRECTORY/.bin/sccache-0.2.13-x86_64-unknown-linux-musl/sccache $CIRCLE_WORKING_DIRECTORY/.bin/sccache
            export PATH="$PATH:$CIRCLE_WORKING_DIRECTORY/.bin"
            export RUSTC_WRAPPER="sccache"
            rm -rf "$CIRCLE_WORKING_DIRECTORY/.cargo/registry"
            sudo apt-get update && sudo apt-get install -y clang llvm-dev llvm pkg-config xz-utils make libssl-dev libssl-dev
      - restore_cache:
          keys:
            - << parameters.cache_key >>
  clear_environment:
    description: "Clear environment"
    parameters:
      cache_key:
        type: string
        default: snarkvm-stable-cache
    steps:
      - run: (sccache -s||true)
      - run: set +e
      - save_cache:
          key: << parameters.cache_key >>
          paths:
            - .cache/sccache
            - .cargo
jobs:

  integration:
    docker:
      - image: cimg/rust:1.53.0
    resource_class: 2xlarge
    steps:
      - checkout
      - setup_environment:
          cache_key: snarkvm-stable-cache
      - run:
          name: Build and run tests
          no_output_timeout: 60m
          command: cd .integration && RUST_MIN_STACK=67108864 cargo test
      - persist_to_workspace:
          root: ~/
          paths: project/
      - clear_environment:
          cache_key: snarkvm-stable-cache

  codecov:
    machine:
      image: ubuntu-1604:202004-01
      docker_layer_caching: true
    resource_class: 2xlarge
    steps:
      - attach_workspace:
          at: /home/circleci/project/
      - run:
          name: Run kcov
          command: >
            cd ~/project/project/ &&
            docker run --security-opt seccomp=unconfined -v ~/project/project/:/home/circleci/project/
            howardwu/snarkos-codecov:2021-03-25 bash /home/circleci/project/.resources/kcov.sh
      - run: cd ./project/ && bash <(curl -s https://codecov.io/bash)

  integration-nightly:
    docker:
      - image: howardwu/snarkos-ci:2021-03-25
    resource_class: 2xlarge
    steps:
      - checkout
      - setup_environment:
          cache_key: snarkvm-nightly-cache
      - run:
          name: Build and test
          no_output_timeout: 60m
          command: cd .integration && RUST_MIN_STACK=67108864 cargo test
      - clear_environment:
          cache_key: snarkvm-nightly-cache

  algorithms:
    docker:
      - image: cimg/rust:1.53.0
    resource_class: xlarge
    steps:
      - checkout
      - setup_environment:
          cache_key: snarkvm-algorithms-cache
      - run:
          name: Build and run tests
          no_output_timeout: 35m
          command: cd algorithms && RUST_MIN_STACK=67108864 cargo test
      - clear_environment:
          cache_key: snarkvm-algorithms-cache

  curves:
    docker:
      - image: cimg/rust:1.53.0
    resource_class: xlarge
    steps:
      - checkout
      - setup_environment:
          cache_key: snarkvm-curves-cache
      - run:
          name: Build and run tests
          no_output_timeout: 35m
          command: cd curves && RUST_MIN_STACK=67108864 cargo test
      - clear_environment:
          cache_key: snarkvm-curves-cache

  derives:
    docker:
      - image: cimg/rust:1.53.0
    resource_class: xlarge
    steps:
      - checkout
      - setup_environment:
          cache_key: snarkvm-derives-cache
      - run:
          name: Build and run tests
          no_output_timeout: 35m
          command: cd derives && RUST_MIN_STACK=67108864 cargo test
      - clear_environment:
          cache_key: snarkvm-derives-cache

  dpc:
    docker:
      - image: cimg/rust:1.53.0
    resource_class: xlarge
    steps:
      - checkout
      - setup_environment:
          cache_key: snarkvm-dpc-cache
      - run:
          name: Build and run tests
          no_output_timeout: 35m
          command: cd dpc && RUST_MIN_STACK=67108864 cargo test
      - clear_environment:
          cache_key: snarkvm-dpc-cache

  fields:
    docker:
      - image: cimg/rust:1.53.0
    resource_class: xlarge
    steps:
      - checkout
      - setup_environment:
          cache_key: snarkvm-fields-cache
      - run:
          name: Build and run tests
          no_output_timeout: 35m
          command: cd fields && RUST_MIN_STACK=67108864 cargo test
      - clear_environment:
          cache_key: snarkvm-fields-cache

  gadgets:
    docker:
      - image: cimg/rust:1.53.0
    resource_class: xlarge
    steps:
      - checkout
      - setup_environment:
          cache_key: snarkvm-gadgets-cache
      - run:
          name: Build and run tests
          no_output_timeout: 35m
          command: cd gadgets && RUST_MIN_STACK=67108864 cargo test
      - clear_environment:
          cache_key: snarkvm-gadgets-cache

  marlin:
    docker:
      - image: cimg/rust:1.53.0
    resource_class: xlarge
    steps:
      - checkout
      - setup_environment:
          cache_key: snarkvm-marlin-cache
      - run:
          name: Build and run tests
          no_output_timeout: 35m
          command: cd marlin && RUST_MIN_STACK=67108864 cargo test
      - clear_environment:
          cache_key: snarkvm-marlin-cache

  parameters:
    docker:
      - image: cimg/rust:1.53.0
    resource_class: xlarge
    steps:
      - checkout
      - setup_environment:
          cache_key: snarkvm-parameters-cache
      - run:
          name: Build and run tests
          no_output_timeout: 35m
          command: cd parameters && RUST_MIN_STACK=67108864 cargo test
      - clear_environment:
          cache_key: snarkvm-parameters-cache

  polycommit:
    docker:
      - image: cimg/rust:1.53.0
    resource_class: xlarge
    steps:
      - checkout
      - setup_environment:
          cache_key: snarkvm-polycommit-cache
      - run:
          name: Build and run tests
          no_output_timeout: 35m
          command: cd polycommit && RUST_MIN_STACK=67108864 cargo test
      - clear_environment:
          cache_key: snarkvm-polycommit-cache

  posw:
    docker:
      - image: cimg/rust:1.53.0
    resource_class: xlarge
    steps:
      - checkout
      - setup_environment:
          cache_key: snarkvm-posw-cache
      - run:
          name: Build and run tests
          no_output_timeout: 35m
          command: cd posw && RUST_MIN_STACK=67108864 cargo test
      - clear_environment:
          cache_key: snarkvm-posw-cache

  profiler:
    docker:
      - image: cimg/rust:1.53.0
    resource_class: xlarge
    steps:
      - checkout
      - setup_environment:
          cache_key: snarkvm-profiler-cache
      - run:
          name: Build and run tests
          no_output_timeout: 35m
          command: cd profiler && RUST_MIN_STACK=67108864 cargo test
      - clear_environment:
          cache_key: snarkvm-profiler-cache

  r1cs:
    docker:
      - image: cimg/rust:1.53.0
    resource_class: xlarge
    steps:
      - checkout
      - setup_environment:
          cache_key: snarkvm-r1cs-cache
      - run:
          name: Build and run tests
          no_output_timeout: 35m
          command: cd r1cs && RUST_MIN_STACK=67108864 cargo test
      - clear_environment:
          cache_key: snarkvm-r1cs-cache

  utilities:
    docker:
      - image: cimg/rust:1.53.0
    resource_class: xlarge
    steps:
      - checkout
      - setup_environment:
          cache_key: snarkvm-utilities-cache
      - run:
          name: Build and run tests
          no_output_timeout: 35m
          command: cd utilities && RUST_MIN_STACK=67108864 cargo test
      - clear_environment:
          cache_key: snarkvm-utilities-cache

  algorithms-nightly:
    docker:
      - image: howardwu/snarkos-ci:2021-03-25
    resource_class: xlarge
    steps:
      - checkout
      - setup_environment:
          cache_key: snarkvm-algorithms-nightly-cache
      - run:
          name: Build and run tests
          no_output_timeout: 35m
          command: cd algorithms && RUST_MIN_STACK=67108864 cargo test
      - clear_environment:
          cache_key: snarkvm-algorithms-nightly-cache

  curves-nightly:
    docker:
      - image: howardwu/snarkos-ci:2021-03-25
    resource_class: xlarge
    steps:
      - checkout
      - setup_environment:
          cache_key: snarkvm-curves-nightly-cache
      - run:
          name: Build and run tests
          no_output_timeout: 35m
          command: cd curves && RUST_MIN_STACK=67108864 cargo test
      - clear_environment:
          cache_key: snarkvm-curves-nightly-cache

  derives-nightly:
    docker:
      - image: howardwu/snarkos-ci:2021-03-25
    resource_class: xlarge
    steps:
      - checkout
      - setup_environment:
          cache_key: snarkvm-derives-nightly-cache
      - run:
          name: Build and run tests
          no_output_timeout: 35m
          command: cd derives && RUST_MIN_STACK=67108864 cargo test
      - clear_environment:
          cache_key: snarkvm-derives-nightly-cache

  dpc-nightly:
    docker:
      - image: howardwu/snarkos-ci:2021-03-25
    resource_class: xlarge
    steps:
      - checkout
      - setup_environment:
          cache_key: snarkvm-dpc-nightly-cache
      - run:
          name: Build and run tests
          no_output_timeout: 35m
          command: cd dpc && RUST_MIN_STACK=67108864 cargo test
      - clear_environment:
          cache_key: snarkvm-dpc-nightly-cache

  fields-nightly:
    docker:
      - image: howardwu/snarkos-ci:2021-03-25
    resource_class: xlarge
    steps:
      - checkout
      - setup_environment:
          cache_key: snarkvm-fields-nightly-cache
      - run:
          name: Build and run tests
          no_output_timeout: 35m
          command: cd fields && RUST_MIN_STACK=67108864 cargo test
      - clear_environment:
          cache_key: snarkvm-fields-nightly-cache

  gadgets-nightly:
    docker:
      - image: howardwu/snarkos-ci:2021-03-25
    resource_class: xlarge
    steps:
      - checkout
      - setup_environment:
          cache_key: snarkvm-gadgets-nightly-cache
      - run:
          name: Build and run tests
          no_output_timeout: 35m
          command: cd gadgets && RUST_MIN_STACK=671088640 cargo test
      - clear_environment:
          cache_key: snarkvm-gadgets-nightly-cache

  marlin-nightly:
    docker:
      - image: howardwu/snarkos-ci:2021-03-25
    resource_class: xlarge
    steps:
      - checkout
      - setup_environment:
          cache_key: snarkvm-marlin-nightly-cache
      - run:
          name: Build and run tests
          no_output_timeout: 35m
          command: cd marlin && RUST_MIN_STACK=67108864 cargo test
      - clear_environment:
          cache_key: snarkvm-marlin-nightly-cache

  parameters-nightly:
    docker:
      - image: howardwu/snarkos-ci:2021-03-25
    resource_class: xlarge
    steps:
      - checkout
      - setup_environment:
          cache_key: snarkvm-parameters-nightly-cache
      - run:
          name: Build and run tests
          no_output_timeout: 35m
          command: cd parameters && RUST_MIN_STACK=67108864 cargo test
      - clear_environment:
          cache_key: snarkvm-parameters-nightly-cache

  polycommit-nightly:
    docker:
      - image: howardwu/snarkos-ci:2021-03-25
    resource_class: xlarge
    steps:
      - checkout
      - setup_environment:
          cache_key: snarkvm-polycommit-nightly-cache
      - run:
          name: Build and run tests
          no_output_timeout: 35m
          command: cd polycommit && RUST_MIN_STACK=67108864 cargo test
      - clear_environment:
          cache_key: snarkvm-polycommit-nightly-cache

  posw-nightly:
    docker:
      - image: howardwu/snarkos-ci:2021-03-25
    resource_class: xlarge
    steps:
      - checkout
      - setup_environment:
          cache_key: snarkvm-posw-nightly-cache
      - run:
          name: Build and run tests
          no_output_timeout: 35m
          command: cd posw && RUST_MIN_STACK=67108864 cargo test
      - clear_environment:
          cache_key: snarkvm-posw-nightly-cache

  profiler-nightly:
    docker:
      - image: howardwu/snarkos-ci:2021-03-25
    resource_class: xlarge
    steps:
      - checkout
      - setup_environment:
          cache_key: snarkvm-profiler-nightly-cache
      - run:
          name: Build and run tests
          no_output_timeout: 35m
          command: cd profiler && RUST_MIN_STACK=67108864 cargo test
      - clear_environment:
          cache_key: snarkvm-profiler-nightly-cache

  r1cs-nightly:
    docker:
      - image: howardwu/snarkos-ci:2021-03-25
    resource_class: xlarge
    steps:
      - checkout
      - setup_environment:
          cache_key: snarkvm-r1cs-nightly-cache
      - run:
          name: Build and run tests
          no_output_timeout: 35m
          command: cd r1cs && RUST_MIN_STACK=67108864 cargo test
      - clear_environment:
          cache_key: snarkvm-r1cs-nightly-cache

  utilities-nightly:
    docker:
      - image: howardwu/snarkos-ci:2021-03-25
    resource_class: xlarge
    steps:
      - checkout
      - setup_environment:
          cache_key: snarkvm-utilities-nightly-cache
      - run:
          name: Build and run tests
          no_output_timeout: 35m
          command: cd utilities && RUST_MIN_STACK=67108864 cargo test
      - clear_environment:
          cache_key: snarkvm-utilities-nightly-cache

  fmt:
    docker:
      - image: howardwu/snarkos-ci:2021-03-25
    resource_class: xlarge
    steps:
      - checkout
      - setup_environment:
          cache_key: snarkvm-fmt-cache
      - run:
          name: Check style
          no_output_timeout: 35m
          command: cargo fmt --all -- --check
      - clear_environment:
          cache_key: snarkvm-fmt-cache

workflows:
  version: 2
  main-workflow:
    jobs:
      - integration
      - integration-nightly
      - codecov:
          requires:
            - integration
            - algorithms
            - curves
            - derives
            - dpc
            - fields
            - gadgets
            - marlin
            - parameters
            - polycommit
            - posw
            - profiler
            - r1cs
            - utilities
      - algorithms
      - curves
      - derives
      - dpc
      - fields
      - gadgets
      - marlin
      - parameters
      - polycommit
      - posw
      - profiler
      - r1cs
      - utilities
      - algorithms-nightly
      - curves-nightly
      - derives-nightly
      - dpc-nightly
      - fields-nightly
      - gadgets-nightly
      - marlin-nightly
      - parameters-nightly
      - polycommit-nightly
      - posw-nightly
      - profiler-nightly
      - r1cs-nightly
      - utilities-nightly
