version: 2.1
commands:
  setup_environment:
    description: "Setup testing environment"
    parameters:
      cache_key:
        type: string
        default: snarkvm-stable-cache
    steps:
      - run: set -e
      - setup_remote_docker
      - run:
          name: Prepare environment and install dependencies
          command: |
            export SCCACHE_CACHE_SIZE=200M
            export WORK_DIR="$CIRCLE_WORKING_DIRECTORY/.cache/sccache"
            export SCCACHE_DIR="$CIRCLE_WORKING_DIRECTORY/.cache/sccache"
            mkdir -p "$CIRCLE_WORKING_DIRECTORY/.bin"
            wget https://github.com/mozilla/sccache/releases/download/0.2.13/sccache-0.2.13-x86_64-unknown-linux-musl.tar.gz
            tar -C "$CIRCLE_WORKING_DIRECTORY/.bin" -xvf sccache-0.2.13-x86_64-unknown-linux-musl.tar.gz
            mv $CIRCLE_WORKING_DIRECTORY/.bin/sccache-0.2.13-x86_64-unknown-linux-musl/sccache $CIRCLE_WORKING_DIRECTORY/.bin/sccache
            export PATH="$PATH:$CIRCLE_WORKING_DIRECTORY/.bin"
            export RUSTC_WRAPPER="sccache"
            rm -rf "$CIRCLE_WORKING_DIRECTORY/.cargo/registry"
            sudo apt-get update && sudo apt-get install -y clang llvm-dev llvm pkg-config xz-utils make libssl-dev libssl-dev
      - restore_cache:
          keys:
            - << parameters.cache_key >>

  clear_environment:
    description: "Clear environment"
    parameters:
      cache_key:
        type: string
        default: snarkvm-stable-cache
    steps:
      - run: (sccache -s||true)
      - run: set +e
      - save_cache:
          key: << parameters.cache_key >>
          paths:
            - .cache/sccache
            - .cargo

  install-rust:
    steps:
      - run:
          name: Installing Rust
          command: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - run:
          name: Setup custom environment variables
          command: |
            echo 'export PATH=$HOME/.cargo/bin:$PATH' >> $BASH_ENV

  setup-rust-toolchain:
    parameters:
      rust-version:
        type: string
        default: "stable"
    steps:
      - run:
          name: Setup Rust toolchain
          command: |
            rustup install <<parameters.rust-version>>
            rustup default <<parameters.rust-version>>
            rustc --version

  install-mingw:
    steps:
      - run:
          name: Install mingw
          command: |
            sudo apt update
            sudo apt install -y gcc-mingw-w64 # This package contains tools for both i686 and x86_64 targets
      - run:
          name: Add mingw target
          command: |
            rustup target add x86_64-pc-windows-gnu
            rustup target add i686-pc-windows-gnu
            # Set the linker to use for Rust/mingw
            echo '[target.x86_64-pc-windows-gnu]' >> ~/.cargo/config
            echo 'linker = "/usr/bin/x86_64-w64-mingw32-gcc"' >> ~/.cargo/config
            echo '[target.i686-pc-windows-gnu]' >> ~/.cargo/config
            echo 'linker = "/usr/bin/i686-w64-mingw32-gcc"' >> ~/.cargo/config

  setup-windows-x86_64:
    steps:
      - install-rust
      - setup-rust-toolchain
      - install-mingw

  setup-windows-i686:
    steps:
      - install-rust
      - setup-rust-toolchain:
          rust-version: "1.56.1"
      - install-mingw

jobs:

  check-windows-x86_64:
    docker:
      - image: cimg/base
    steps:
      - checkout
      - setup-windows-x86_64
      - run:
          name: Check cargo build
          command: cargo build --examples --all --benches

  check-windows-i686:
    docker:
      - image: cimg/base
    steps:
      - checkout
      - setup-windows-i686
      - run:
          name: Check cargo build
          command: cargo build --examples --all --benches

  integration-testnet1:
    docker:
      - image: cimg/rust:1.56.1
    resource_class: 2xlarge
    steps:
      - checkout
      - setup_environment:
          cache_key: snarkvm-stable-testnet1-cache
      - run:
          name: Build and run tests
          no_output_timeout: 60m
          command: cd .integration && RUST_MIN_STACK=67108864 cargo test testnet1
      - persist_to_workspace:
          root: ~/
          paths: project/
      - clear_environment:
          cache_key: snarkvm-stable-testnet1-cache

  integration-testnet2:
    docker:
      - image: cimg/rust:1.56.1
    resource_class: 2xlarge
    steps:
      - checkout
      - setup_environment:
          cache_key: snarkvm-stable-testnet2-cache
      - run:
          name: Build and run tests
          no_output_timeout: 60m
          command: cd .integration && RUST_MIN_STACK=67108864 cargo test testnet2
      - clear_environment:
          cache_key: snarkvm-stable-testnet2-cache

  algorithms:
    docker:
      - image: cimg/rust:1.56.1
    resource_class: 2xlarge
    steps:
      - checkout
      - setup_environment:
          cache_key: snarkvm-algorithms-cache
      - run:
          name: Build and run tests
          no_output_timeout: 35m
          command: cd algorithms && RUST_MIN_STACK=67108864 cargo test
      - clear_environment:
          cache_key: snarkvm-algorithms-cache

  curves:
    docker:
      - image: cimg/rust:1.56.1
    resource_class: 2xlarge
    steps:
      - checkout
      - setup_environment:
          cache_key: snarkvm-curves-cache
      - run:
          name: Build and run tests
          no_output_timeout: 35m
          command: cd curves && RUST_MIN_STACK=67108864 cargo test
      - clear_environment:
          cache_key: snarkvm-curves-cache

  derives:
    docker:
      - image: cimg/rust:1.56.1
    resource_class: 2xlarge
    steps:
      - checkout
      - setup_environment:
          cache_key: snarkvm-derives-cache
      - run:
          name: Build and run tests
          no_output_timeout: 35m
          command: cd derives && RUST_MIN_STACK=67108864 cargo test
      - clear_environment:
          cache_key: snarkvm-derives-cache

  dpc:
    docker:
      - image: cimg/rust:1.56.1
    resource_class: 2xlarge
    steps:
      - checkout
      - setup_environment:
          cache_key: snarkvm-dpc-cache
      - run:
          name: Build and run tests
          no_output_timeout: 35m
          command: cd dpc && RUST_MIN_STACK=67108864 cargo test
      - clear_environment:
          cache_key: snarkvm-dpc-cache

  fields:
    docker:
      - image: cimg/rust:1.56.1
    resource_class: 2xlarge
    steps:
      - checkout
      - setup_environment:
          cache_key: snarkvm-fields-cache
      - run:
          name: Build and run tests
          no_output_timeout: 35m
          command: cd fields && RUST_MIN_STACK=67108864 cargo test
      - clear_environment:
          cache_key: snarkvm-fields-cache

  gadgets:
    docker:
      - image: cimg/rust:1.56.1
    resource_class: 2xlarge
    steps:
      - checkout
      - setup_environment:
          cache_key: snarkvm-gadgets-cache
      - run:
          name: Build and run tests
          no_output_timeout: 35m
          command: cd gadgets && RUST_MIN_STACK=67108864 cargo test
      - clear_environment:
          cache_key: snarkvm-gadgets-cache

  marlin:
    docker:
      - image: cimg/rust:1.56.1
    resource_class: 2xlarge
    steps:
      - checkout
      - setup_environment:
          cache_key: snarkvm-marlin-cache
      - run:
          name: Build and run tests
          no_output_timeout: 35m
          command: cd marlin && RUST_MIN_STACK=67108864 cargo test
      - clear_environment:
          cache_key: snarkvm-marlin-cache

  parameters:
    docker:
      - image: cimg/rust:1.56.1
    resource_class: 2xlarge
    steps:
      - checkout
      - setup_environment:
          cache_key: snarkvm-parameters-cache
      - run:
          name: Build and run tests
          no_output_timeout: 35m
          command: cd parameters && RUST_MIN_STACK=67108864 cargo test
      - clear_environment:
          cache_key: snarkvm-parameters-cache

  polycommit:
    docker:
      - image: cimg/rust:1.56.1
    resource_class: 2xlarge
    steps:
      - checkout
      - setup_environment:
          cache_key: snarkvm-polycommit-cache
      - run:
          name: Build and run tests
          no_output_timeout: 35m
          command: cd polycommit && RUST_MIN_STACK=67108864 cargo test
      - clear_environment:
          cache_key: snarkvm-polycommit-cache

  profiler:
    docker:
      - image: cimg/rust:1.56.1
    resource_class: 2xlarge
    steps:
      - checkout
      - setup_environment:
          cache_key: snarkvm-profiler-cache
      - run:
          name: Build and run tests
          no_output_timeout: 35m
          command: cd profiler && RUST_MIN_STACK=67108864 cargo test
      - clear_environment:
          cache_key: snarkvm-profiler-cache

  r1cs:
    docker:
      - image: cimg/rust:1.56.1
    resource_class: 2xlarge
    steps:
      - checkout
      - setup_environment:
          cache_key: snarkvm-r1cs-cache
      - run:
          name: Build and run tests
          no_output_timeout: 35m
          command: cd r1cs && RUST_MIN_STACK=67108864 cargo test
      - clear_environment:
          cache_key: snarkvm-r1cs-cache

  utilities:
    docker:
      - image: cimg/rust:1.56.1
    resource_class: 2xlarge
    steps:
      - checkout
      - setup_environment:
          cache_key: snarkvm-utilities-cache
      - run:
          name: Build and run tests
          no_output_timeout: 35m
          command: cd utilities && RUST_MIN_STACK=67108864 cargo test
      - clear_environment:
          cache_key: snarkvm-utilities-cache

  fmt:
    docker:
      - image: howardwu/snarkos-ci:2021-03-25
    resource_class: 2xlarge
    steps:
      - checkout
      - setup_environment:
          cache_key: snarkvm-fmt-cache
      - run:
          name: Check style
          no_output_timeout: 35m
          command: cargo fmt --all -- --check
      - clear_environment:
          cache_key: snarkvm-fmt-cache

workflows:
  version: 2
  main-workflow:
    jobs:
      - check-windows-x86_64
      - check-windows-i686
      - integration-testnet1
      - integration-testnet2
      - algorithms
      - curves
      - derives
      - dpc
      - fields
      - gadgets
      - marlin
      - parameters
      - polycommit
      - profiler
      - r1cs
      - utilities
      - fmt
