[package]
name = "snarkvm-dpc"
version = "0.2.2"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "DPC for a decentralized virtual machine"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkVM"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [ "cryptography::cryptocurrencies", "operating-systems" ]
include = [ "Cargo.toml", "src", "README.md", "LICENSE.md" ]
license = "GPL-3.0"
edition = "2018"

[dependencies.snarkvm-algorithms]
path = "../algorithms"
version = "0.2.2"
default-features = false

[dependencies.snarkvm-curves]
path = "../curves"
version = "0.2.2"
default-features = false

[dependencies.snarkvm-fields]
path = "../fields"
version = "0.2.2"
default-features = false

[dependencies.snarkvm-gadgets]
path = "../gadgets"
version = "0.2.2"
default-features = false

[dependencies.snarkvm-objects]
path = "../objects"
version = "0.2.2"
default-features = false

[dependencies.snarkvm-parameters]
path = "../parameters"
version = "0.2.2"
default-features = false

[dependencies.snarkvm-profiler]
path = "../profiler"
version = "0.2.2"
default-features = false

[dependencies.snarkvm-r1cs]
path = "../r1cs"
version = "0.2.2"
default-features = false

[dependencies.snarkvm-utilities]
path = "../utilities"
version = "0.2.2"
default-features = false

[dependencies.anyhow]
version = "1.0.40"

[dependencies.base58]
version = "0.1"

[dependencies.bech32]
version = "0.8"

[dependencies.blake2]
version = "0.9"

[dependencies.derivative]
version = "2"

[dependencies.hex]
version = "0.4.3"

[dependencies.itertools]
version = "0.10.0"

[dependencies.rand]
version = "0.8"

[dependencies.thiserror]
version = "1.0"

[dev-dependencies.rand_xorshift]
version = "0.3"

[features]
default = [
  "snarkvm-algorithms/default",
  "snarkvm-curves/default",
  "snarkvm-gadgets/default",
  "snarkvm-parameters/default",
  "snarkvm-utilities/default"
]
print-trace = [ "snarkvm-profiler/print-trace" ]
