[package]
name = "snarkvm-circuit-collections"
version = "0.16.19"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Collections circuit library for a decentralized virtual machine"
license = "Apache-2.0"
edition = "2021"

# Dependencies
[dependencies]
console = { package = "snarkvm-console-collections", path = "../../console/collections", version = "=0.16.19", optional = true }
snarkvm-circuit-algorithms = { path = "../algorithms", version = "=0.16.19" }
snarkvm-circuit-types = { path = "../types", version = "=0.16.19" }

# Dev dependencies
[dev-dependencies]
snarkvm-circuit-network = { path = "../network" }
snarkvm-console-algorithms = { path = "../../console/algorithms" }
snarkvm-console-network = { path = "../../console/network" }
snarkvm-utilities = { path = "../../utilities" }
anyhow = "1.0.73"

# Features
[features]
default = ["enable_console"]
enable_console = ["console"]

