[package]
name = "snarkvm-circuits-scope"
version = "0.7.5"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "A procedural macro to construct scope in an environment"
license = "GPL-3.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "0.6"
proc-macro2 = "0.4"

[dependencies.snarkvm-circuits-environment]
path = "../environment"
version = "0.7.5"

[dependencies.syn]
version = "0.15.42"
features = ["full"]

[features]
default = []
scope = []
