[package]
name = "snarkvm-ledger-test-helpers"
version = "0.16.3"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Test helpers for a decentralized virtual machine"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkVM"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [ "cryptography", "web-programming" ]
license = "Apache-2.0"
edition = "2021"

[dependencies.console]
package = "snarkvm-console"
path = "../../console"
version = "=0.16.3"

[dependencies.circuit]
package = "snarkvm-circuit"
path = "../../circuit"
version = "=0.16.3"

[dependencies.ledger-block]
package = "snarkvm-ledger-block"
path = "../block"
version = "=0.16.3"
features = [ "test-helpers" ]

[dependencies.ledger-query]
package = "snarkvm-ledger-query"
path = "../query"
version = "=0.16.3"
default-features = false
features = [ "query" ]

[dependencies.ledger-store]
package = "snarkvm-ledger-store"
path = "../store"
version = "=0.16.3"

[dependencies.synthesizer-program]
package = "snarkvm-synthesizer-program"
path = "../../synthesizer/program"
version = "=0.16.3"
features = [ "test-helpers" ]

[dependencies.synthesizer-process]
package = "snarkvm-synthesizer-process"
path = "../../synthesizer/process"
version = "=0.16.3"

[dependencies.once_cell]
version = "1.18"
