[package]
name = "snarkvm-circuit-program"
version = "0.9.0"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Program circuit library for a decentralized virtual machine"
license = "GPL-3.0"
edition = "2021"

[dependencies.console]
package = "snarkvm-console-program"
path = "../../console/program"
version = "0.9.0"
optional = true

[dependencies.snarkvm-circuit-account]
path = "../account"
version = "0.9.0"
default-features = false

[dependencies.snarkvm-circuit-network]
path = "../network"
version = "0.9.0"
default-features = false

[dependencies.snarkvm-circuit-types]
path = "../types"
version = "0.9.0"
default-features = false

[dependencies.snarkvm-utilities]
path = "../../utilities"
version = "0.9.0"
default-features = false

[dev-dependencies.snarkvm-console-account]
path = "../../console/account"

[dev-dependencies.anyhow]
version = "1.0.64"

[dev-dependencies.rand]
version = "0.8"

[features]
default = [
    "enable_console",
    "snarkvm-circuit-account/default",
    "snarkvm-circuit-network/default",
    "snarkvm-circuit-types/default",
    "snarkvm-utilities/default"
]
enable_console = [ "console" ]
enclave = [
    "snarkvm-circuit-account/enclave",
    "snarkvm-circuit-network/enclave",
    "snarkvm-circuit-types/enclave",
    "snarkvm-utilities/enclave"
]
