[package]
name = "snarkvm-console"
version = "0.9.0"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Console environment for a decentralized virtual machine"
license = "GPL-3.0"
edition = "2021"

[dependencies.snarkvm-console-account]
path = "./account"
version = "0.9.0"
optional = true
default-features = false

[dependencies.snarkvm-console-algorithms]
path = "./algorithms"
version = "0.9.0"
optional = true
default-features = false

[dependencies.snarkvm-console-collections]
path = "./collections"
version = "0.9.0"
optional = true
default-features = false

[dependencies.snarkvm-console-network]
path = "./network"
version = "0.9.0"
optional = true
default-features = false

[dependencies.snarkvm-console-program]
path = "./program"
version = "0.9.0"
optional = true
default-features = false

[dependencies.snarkvm-console-types]
path = "./types"
version = "0.9.0"
optional = true

[features]
default = [
  "parallel",
  "account",
  "algorithms",
  "collections",
  "network",
  "program",
  "types"
]
parallel = [ "snarkvm-console-collections/parallel" ]
account = [ "network", "snarkvm-console-account/default" ]
algorithms = [ "snarkvm-console-algorithms/default" ]
collections = [ "algorithms", "snarkvm-console-collections/default" ]
network = [ "collections", "snarkvm-console-network/default" ]
program = [ "network", "snarkvm-console-program/default" ]
types = [ "snarkvm-console-types" ]
enclave = [ 
  "snarkvm-console-account/enclave",
  "snarkvm-console-algorithms/enclave",
  "snarkvm-console-collections/enclave",
  "snarkvm-console-network/enclave",
  "snarkvm-console-program/enclave" ]
