[package]
name = "snarkvm-circuit-types-scalar"
version = "0.9.0"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Scalar circuit for a decentralized virtual machine"
license = "GPL-3.0"
edition = "2021"

[dependencies.console]
package = "snarkvm-console-types-scalar"
path = "../../../console/types/scalar"
version = "0.9.0"
optional = true

[dependencies.snarkvm-circuit-environment]
path = "../../environment"
version = "0.9.0"
default-features = false

[dependencies.snarkvm-circuit-types-boolean]
path = "../boolean"
version = "0.9.0"
default-features = false

[dependencies.snarkvm-circuit-types-field]
path = "../field"
version = "0.9.0"
default-features = false

[features]
default = [
    "enable_console",
    "snarkvm-circuit-environment/default",
    "snarkvm-circuit-types-boolean/default",
    "snarkvm-circuit-types-field/default"
]
enable_console = [ "console" ]
enclave = [
    "snarkvm-circuit-environment/enclave",
    "snarkvm-circuit-types-boolean/enclave",
    "snarkvm-circuit-types-field/enclave",
    "enable_console"
]
