[package]
name = "snarkvm-console-types-field"
version = "0.9.0"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Type operations for a decentralized virtual machine"
license = "GPL-3.0"
edition = "2021"

[features]
default = []
fuzzing = ["arbitrary"]

[dependencies.snarkvm-console-network-environment]
path = "../../network/environment"
version = "0.9.0"

[dependencies.snarkvm-console-types-boolean]
path = "../boolean"
version = "0.9.0"

[dependencies.arbitrary]
version = "1"
features = ["derive"]
optional = true

[dev-dependencies.bincode]
version = "1.3"

[dev-dependencies.serde_json]
version = "1.0"
