[package]
name = "snarkvm-circuits-programs"
version = "0.7.5"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Programs for a decentralized virtual machine"
license = "GPL-3.0"
edition = "2021"

[dependencies.snarkvm-circuits]
path = ".."
version = "0.7.5"
default-features = false

[dependencies.snarkvm-curves]
path = "../../curves"
version = "0.7.5"
default-features = false

[dependencies.snarkvm-fields]
path = "../../fields"
version = "0.7.5"
default-features = false

[dependencies.snarkvm-r1cs]
path = "../../r1cs"
version = "0.7.5"
default-features = false

[dependencies.nom]
version = "7.1"

[dependencies.once_cell]
version = "1.8.0"

[dependencies.rayon]
version = "1"

[dev-dependencies.snarkvm-algorithms]
path = "../../algorithms"
version = "0.7.5"
default-features = false
features = ["polycommit", "snark"]

[dev-dependencies.snarkvm-circuits]
path = "../../circuits"
version = "0.7.5"

[dev-dependencies.snarkvm-utilities]
path = "../../utilities"
version = "0.7.5"
default-features = false

[features]
default = ["snarkvm-circuits/default", "snarkvm-curves/default", "snarkvm-r1cs/default"]
