name: checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Install Rust 1.61.0
      uses: actions-rs/toolchain@v1
      with:
          toolchain: 1.61.0
          override: true
          components: rustfmt, clippy
    - uses: actions/checkout@v3
    # - name: format
    #   run: cargo fmt --all -- --check
    # - name: Build
    #   run: cargo build --release
    # - name: Run tests
    #   run: cargo test
    # - name: Run clippy
    #   run: cargo clippy  -- -D warnings
    - name: Coverage
      run: docker run --security-opt seccomp=unconfined -v "${PWD}:/volume" xd009642/tarpaulin cargo tarpaulin -t 1800
    # - name: Upload coverage to codecov.io
    #   uses: codecov/codecov-action@v2
    #   with:
    #     fail_ci_if_error:     true
